accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    # path("account/login", views.loginView,name="login"),
    path("signup/",views.registerView,name="signup"),
    path('<pk>/update', views.UserEditView.as_view(), name="edit_profile"),

]

blog/urls.py
from unicodedata import name
from django.urls import path
from .views import Myview, post_list, post_detail
from .views import contact
from .views import book_list,loginView,profileView,logout_view

app_name="blog"



urlpatterns = [
    path("books_list/", book_list),
    path("", post_list),
    path("contact/", contact),
    path("about/",Myview.as_view(), name = "home"),
    path("<int:year>/<int:month>/<int:day>/<slug:post>/", post_detail, name="post_detail"),
    path("login/",loginView, name= "login"),
    path("profile/", profileView, name="profile"),
    path("logout/", logout_view, name='logout')
]

introtodjango/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("blog.urls")),
    path("products/",include("ecommerce.urls")),
    path('accounts/', include('accounts.urls'))
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
import email
from email.policy import default
from turtle import update
from unicodedata import name
from django.utils import timezone
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    isbn = models.CharField(max_length=13)

    def __str__(self):
        return self.title

class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published'),
    )
    title = models.CharField(max_length=250)
    post_image = models.ImageField(blank=True, null=True)
    slug = models.CharField(max_length=250, unique_for_date='publish')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_post')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    
    class Meta:
        ordering = ('-publish',)
    def __str__(self):
        return self.title    

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,self.publish.month,self.publish.day,self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class meta:
        ordering = ('created',)
    def __str__(self):
        return f'comment by{self.name} on {self.post}'

blog/forms.py
from .models import Comment
from django import forms

#forms
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')

blog/views.py
from multiprocessing import AuthenticationError
from django.views.generic import TemplateView
from django.shortcuts import render, get_object_or_404, redirect
import datetime
from django.http import HttpResponse
from django.views import View
from .models import Book,Post,Comment
from .forms import CommentForm
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


# Create your views here.
def displayTime(request):
    now = datetime.datetime.now()
    html = "Time is{}".format(now)
    return HttpResponse(html)

def contact(request):
    return HttpResponse("Hello This Is Lebza")

# Class-based view
class Myview(TemplateView):
    def get(self, **kwargs):
        context = super().get(**kwargs)
        template_name = "index.html"
        context = {
            "Page":template_name
        }
        return context
        # return Template("This class based view")

# Book_list
def book_list(request):
    books = Book.objects.all()
    return render(request,"book_list.html", {"books": books})

# Post_list
def post_list(request):
    posts = Post.objects.all()
    paginator = Paginator(posts, 1)
    page = request.GET.get('page')
    try:
        posts = paginator.page('page')
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)        
    return render(request,'index.html', {'page': page, 'posts': posts})

# Post_Detail View
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug= post, status='published',publish__year=year,publish__month=month,publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method =='POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post=post
            new_comment.save()
    else:
        comment_form = CommentForm()       
    return render(request, 'post_detail.html', {'post': post,'comments':comments,'new_comment':new_comment,'comment_form':comment_form})



def loginView(request):
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"you are now logged in{username}.")
                return redirect("blog:profile")
            else :
                messages.error(request, f"invalid username or password")
        else :
            messages.error(request, f"invalid username or password")
    form = AuthenticationForm()
    return render(request, 'authenticate/login.html', context={"form":form})

@login_required(login_url='blog:login')
def profileView(request):
    return render(request, "profile.html",{})

def logout_view(request):
    logout(request)
    return redirect('/')

blog/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us</title>
    <link rel="stylesheet" href="../css/app.css">
    <link rel="stylesheet" href="../css/mobile.css">
</head>
<body>
    <header>
        <nav>
            <div class="logo">
                <h1>Deluxe Amps</h1>
            </div>
            <ul class="nav-links">
                <li><a href="../templates/base.html">Home</a></li>
                <li><a href="./about.html">About Us</a></li>
                <li><a href="./contact.html">Contact</a></li>
                <li><a href="./book_list.html">Booklist</a></li>
            </ul>
            <!-- <div class="social">
                <li><a href=""><i class="fab fa-facebook-square"></i></a></li>
                <li><a href=""><i class="fab fa-twitter"></i></a></li>
                <li><a href=""><i class="fab fa-instagram"></i></a></li>
            </div> -->
        </nav>
    </header>
    <div class="w3-col m6 w3-padding-large">
        <h1 class="w3-center">About Good Hope Entertainment</h1><br>
        <h5 class="w3-center">Tradition Since 2005</h5>
        <p class="w3-large">Good Hope Entertainment was founded in blabla by Mr. Smith in lorem ipsum dolor sit amet, consectetur adipiscing elit consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute iruredolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.We only use Sound Equipment.</p>
        <p class="w3-large w3-text-grey w3-hide-medium">Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod temporincididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
      </div>
    
</body>
</html>

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'CSS/app.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/mobile.css' %}">
    <link rel="stylesheet" href="{% static 'JS/app.js' %}">
</head>
<body>
    <nav>
        <div class="logo">
            <h1>Deluxe Amps</h1>
        </div>
        <ul class="nav-links">
            <li><a href="../templates/base.html">Home</a></li>
            <li><a href="./about.html">About Us</a></li>
            <li><a href="./contact.html">Contact</a></li>
            <li><a href="./book_list.html">Booklist</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'blog:logout' %}">logout</a></li>
            {% else %}
            <li>
                <a href="{% url 'blog:login' %}">login</a>
            </li>
            <li>
                <a href="{% url 'accounts:signup' %}">signup</a>
            </li>
            {% endif %}
            
            {% if request.user.is_authenticated %}
            <li>Hello {{request.user}}</li>
            {% endif %}
        </ul>
        <div class="burger">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </nav>
    
    
    <div class="container mt-5">
        {% if message %}
            {% for message in messages %}
            <div class="alert alert-danger mt-5" role="alert">
                {{ message }}
            </div>
            {% endfor %}
        {% endif %}
    </div>
    
    {% block content %}

    {% endblock content %}
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
</body>
<script src="{% static 'js/app.js'%}"></script>
</html>

blog/templates/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>This Is My Book List</h1>
    {% for book in books %}
    <ul>
        <li>Title: {{ book.title }} </li>
        <li>Subtitle: {{ book.subtitle }}</li>
        <li>Author: {{ book.author }}</li>
        <li>ISBN: {{ book.isbn }}</li>
    </ul>
    {% endfor %}
</body>
</html>

blog/templates/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/app.css">
    <link rel="stylesheet" href="../css/mobile.css">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

blog/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block content %}

    {% load static %}
    <img src="{% static 'IMAGE/hDGMiMcc_0scF_fzPnQPaVxwa9et2C3W4kFNSKmHpH8.jpg' %}">

    <!-- <h1>This Is My Post List</h1>
    {% for post in posts %}
    <ul>
        <h1>{{ post.title }}</h1>
        <h1>{{ post.slug }}</h1>
        <h1>{{ post.author }}</h1>
        <h1>{{ post.body }}</h1>
        <h1>{{ post.pulish }}</h1>
    </ul>
    {% endfor %} -->
    
    <h1>This Is My Post List</h1>
    {% for post in posts %}
    <h1>
        <a href="{{ post.get_absolute_url }}">
            {{ post.title }}
        </a>
    </h1>
    {% if post.post_image %}
    <img src="{{ post.post_image.url }}" alt="">
    {% endif %}
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}
{% include "pagination.html" with page=posts %}

{% endblock content %}

blog/templates/pagination.html
<div class="pagination container justify-content-center">
    <ul class="pagination">
        <li class="page-links">
            {%if page.has_previous%}
               <a href="?page ={{page.previous_page_number}}" class="page-link">Previous</a>
            {%endif%}
        </li>
        <li class="page-items page-link">
            Page {{ page.number }}
        </li>
        <li class="page-item page-link">of</li>
        <li class="page-item page-link">page{{ page.number }} of {{page.paginator.num_pages}}</li>
        <li class="page-item">
            {%if page.has_next%}
            <a href="?page ={page.next_page_number}" class="page-link">Next</a>
        {%endif%}
        </li>
    </ul>
</div>

blog/templates/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title%}{{ post.title }}{% endblock %}
{% block content%}
<h1>{{ post.title }}</h1>
{% if post.post_image %}
<img src="{{ post.post_img.url }}" alt="">
{% endif %}
<p class="date">
    Publish {{post.publish}} by {{post.author}}
</p>
{{post.body|linebreaks}}

    <!-- <--comment--> 
<Div class="container">
{% with comments.count as total_comments %}
<h2>
{{ total_comments }} comment {{total_comments|pluralize}}
</h2>
{% endwith %}


{% for comment in comments %}
<div class="comment">
<p class="info">
comment{{forloop.counter}} by {{comment.name}}{{comment.created}}
</p>
{{comment.body|linebreaks}}
</div>
{%empty%}
<p>There are no paragraph</p>
{%endfor%}

{%if new_comment%}
<h2>your comment has been added</h2>
{%else%}
<h2>Add a new comment</h2>
<form method="POST">
{{ comment_form|crispy }}
{% csrf_token %}
<p><input type="submit" value="add comment"></p>
</form>
{%endif%}
</Div>
{%endblock%}
{}

blog/templates/profile.html
{% extends "base.html" %}
{% block content %}
<a href="{% url 'accounts:edit_profile' user.id %}">edit your profile</a>
{% endblock content %}